all:
	cd c1_linear; make
	cd c2_stack; make
	cd c3_queue; make
	cd c4_string; make
	cd c5_tree; make

clean:
	cd c1_linear; make clean
	cd c2_stack; make clean
	cd c3_queue; make clean
	cd c4_string; make clean
	cd c5_tree; make clean